# Generated by Django 2.0.7 on 2020-05-31 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190408_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
