# Generated by Django 2.0.7 on 2020-05-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20190408_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='co2_ppm',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='sensor',
            name='co2_ppm',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='temperature',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='humidity',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sensor',
            name='temperature',
            field=models.FloatField(null=True),
        ),
    ]
